include: package:lints/recommended.yaml
linter:
  rules:
    - prefer_single_quotes
analyzer:
  exclude:
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
