name: setore
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  drift: ^2.15.0
  path: ^1.9.0
  path_provider: ^2.1.2
  sqlite3: ^2.4.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.4
dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  lints: ^3.0.0
  test: ^1.25.2
  riverpod_generator: ^2.4.0
  go_router_builder: ^2.5.1
  freezed: ^2.5.2
