name: setore
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  drift: ^2.15.0
  path: ^1.9.0
  path_provider: ^2.1.2
  sqlcipher_flutter_libs: ^0.6.1
  sqlite3: ^2.4.0
dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  lints: ^3.0.0
  test: ^1.25.2
